syntax = "proto3";
package currency;

option go_package = "protos/currency";

// Service definition, this is what the client will call
// This service will return the currency rate for a given currency
service CurrencyService {
  rpc GetRate (RateRequest) returns (RateResponse) {}
}

// Message definition, this is the data that will be sent to the service
// This message will contain the currency that the client wants the rate for
message RateRequest {
  Currencies base = 1;
  Currencies destination = 2;
}

// Message definition, this is the data that will be sent back to the client
// This message will contain the currency and the rate
message RateResponse {
  float rate = 1;
}


// Currencies is an enum which represents the allowed currencies for the API
enum Currencies {
  EUR=0;
  USD=1;
  JPY=2;
  BGN=3;
  CZK=4;
  DKK=5;
  GBP=6;
  HUF=7;
  PLN=8;
  RON=9;
  SEK=10;
  CHF=11;
  ISK=12;
  NOK=13;
  HRK=14;
  RUB=15;
  TRY=16;
  AUD=17;
  BRL=18;
  CAD=19;
  CNY=20;
  HKD=21;
  IDR=22;
  ILS=23;
  INR=24;
  KRW=25;
  MXN=26;
  MYR=27;
  NZD=28;
  PHP=29;
  SGD=30;
  THB=31;
  ZAR=32;
}